# Generated by Django 5.0.7 on 2024-07-24 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0010_application_allowed_origins'),
        ('student', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('clientid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('clientsecret', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('oauth2_provider.application',),
        ),
    ]
